export const COLLECTIONS = {
  TENANT: 'tenants',
  AGENCY: 'agencies',
  AGENT: 'agents',
  CONSUMER: 'consumers',
  SESSION_TYPE: 'session-types',
  TIME_SLOT: 'time-slots',
  ALLOCATION: 'allocations',
  BUNDLE: 'bundles',
  BUNDLE_USAGE_EVENT: 'bundle-usage-events',
  RESERVATION: 'reservations',
  GROUP_RESERVATION: 'group-reservations',
  SESSION: 'sessions',
  SESSION_CONSUMER: 'session-consumers',
  CONTEXT: 'contexts',
  TAG: 'tags',
  ADDRESS: 'addresses',
  AGENT_SESSION_TYPE_AGENCY: 'agent-session-type-agencies',
  ALT_SESSION_AGENT: 'alt-session-agents',
}
